project_id = "jfogxnstkykpsyeegmnm"

[functions.google-merchant-feed]
verify_jwt = false

[functions.shopify-proxy]
verify_jwt = false

[functions.facebook-catalog-feed]
verify_jwt = false

[functions.flashy-catalog-feed]
verify_jwt = false

[functions.analytics-ai]
verify_jwt = false
